import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import storvoLogo from "@/assets/storvo-logo.png";

const SECTIONS = {
  terms: {
    title: "Terms of Service",
    lastUpdated: "April 16, 2026",
    content: [
      {
        heading: "1. Acceptance of Terms",
        body: `By accessing or using Storvo ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Platform. These terms apply to all visitors, sellers, and buyers who access or use our services.`,
      },
      {
        heading: "2. Description of Service",
        body: `Storvo is a Nigerian e-commerce platform that enables social sellers to create online stores, list products, and accept payments via Paystack. We provide the technology infrastructure; sellers are responsible for their own products, pricing, delivery, and customer service.`,
      },
      {
        heading: "3. Seller Responsibilities",
        body: `Sellers agree to: (a) provide accurate product descriptions and pricing; (b) fulfil orders in a timely manner; (c) comply with all applicable Nigerian laws including consumer protection regulations; (d) not list prohibited items including counterfeit goods, illegal substances, or items that infringe third-party intellectual property rights.`,
      },
      {
        heading: "4. Buyer Responsibilities",
        body: `Buyers agree to: (a) provide accurate delivery information; (b) make payments in good faith; (c) communicate disputes directly with the seller in the first instance before escalating to Storvo support.`,
      },
      {
        heading: "5. Payments",
        body: `All payments are processed by Paystack, a PCI-DSS compliant payment processor. Storvo does not store card details. Transaction fees apply as outlined in the pricing plans. Sellers receive payouts directly to their connected bank account via Paystack subaccounts.`,
      },
      {
        heading: "6. Prohibited Use",
        body: `You may not use the Platform to: engage in fraud or misrepresentation; violate any applicable law or regulation; distribute malware or harmful code; scrape or harvest data without permission; or impersonate another person or entity.`,
      },
      {
        heading: "7. Intellectual Property",
        body: `Storvo and its logos, trademarks, and brand elements are the property of LHF Studio. Sellers retain ownership of their product images and descriptions. By uploading content, sellers grant Storvo a non-exclusive licence to display that content on the Platform.`,
      },
      {
        heading: "8. Limitation of Liability",
        body: `To the maximum extent permitted by Nigerian law, Storvo and LHF Studio shall not be liable for any indirect, incidental, or consequential damages arising from use of the Platform. Our total liability in any matter shall not exceed the fees paid by you to Storvo in the 3 months preceding the claim.`,
      },
      {
        heading: "9. Termination",
        body: `We reserve the right to suspend or terminate any account that violates these Terms of Service, with or without notice. Sellers may close their accounts at any time from their dashboard.`,
      },
      {
        heading: "10. Changes to Terms",
        body: `We may update these Terms from time to time. Continued use of the Platform after changes are posted constitutes acceptance of the revised Terms. We will notify users of material changes via email or in-app notification.`,
      },
      {
        heading: "11. Governing Law",
        body: `These Terms shall be governed by and construed in accordance with the laws of the Federal Republic of Nigeria. Any disputes shall be subject to the exclusive jurisdiction of Nigerian courts.`,
      },
      {
        heading: "12. Contact",
        body: `For questions about these Terms, contact us at legal@storvo.co or through our support channels.`,
      },
    ],
  },
  privacy: {
    title: "Privacy Policy",
    lastUpdated: "April 16, 2026",
    content: [
      {
        heading: "1. Information We Collect",
        body: `We collect information you provide directly (name, email, phone number, bank details for sellers) and information generated by your use of the Platform (store data, orders, product listings, analytics). We also collect technical data such as IP address, browser type, and device identifiers.`,
      },
      {
        heading: "2. How We Use Your Information",
        body: `We use your information to: operate and improve the Platform; process transactions and payouts; send transactional notifications (order confirmations, payment receipts); provide customer support; detect and prevent fraud; and comply with legal obligations under Nigerian law.`,
      },
      {
        heading: "3. Information Sharing",
        body: `We do not sell your personal data. We share information only: (a) with Paystack to process payments; (b) with Supabase for database and authentication services; (c) with sellers when a buyer places an order (name, phone, delivery address); (d) as required by law or legal process in Nigeria.`,
      },
      {
        heading: "4. Buyer Data Shared with Sellers",
        body: `When a buyer places an order, the seller receives the buyer's name, phone number, email (if provided), and delivery address to fulfil the order. Sellers must not use this information for any purpose other than order fulfilment.`,
      },
      {
        heading: "5. Data Security",
        body: `We implement industry-standard security measures including TLS encryption in transit, secure authentication via Supabase, and PCI-DSS compliant payment processing via Paystack. No method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.`,
      },
      {
        heading: "6. Data Retention",
        body: `We retain your personal data for as long as your account is active and for a reasonable period thereafter to comply with legal obligations and resolve disputes. You may request deletion of your data by contacting us.`,
      },
      {
        heading: "7. Cookies",
        body: `We use cookies and similar technologies to maintain authentication sessions and understand how the Platform is used. You can control cookies through your browser settings, but disabling them may affect Platform functionality.`,
      },
      {
        heading: "8. Your Rights",
        body: `Under the Nigeria Data Protection Regulation (NDPR), you have the right to: access the personal data we hold about you; correct inaccurate data; request deletion of your data; object to processing of your data; and lodge a complaint with the National Information Technology Development Agency (NITDA).`,
      },
      {
        heading: "9. Children's Privacy",
        body: `The Platform is not intended for persons under 18 years of age. We do not knowingly collect personal information from minors. If you believe a minor has provided us with personal data, please contact us and we will delete it.`,
      },
      {
        heading: "10. Changes to This Policy",
        body: `We may update this Privacy Policy periodically. We will notify you of significant changes by posting a notice on the Platform or sending an email to your registered address.`,
      },
      {
        heading: "11. Contact",
        body: `For privacy-related queries or to exercise your NDPR rights, contact our Data Protection Officer at privacy@storvo.co.`,
      },
    ],
  },
};

const Legal = () => {
  const navigate = useNavigate();
  const { page } = useParams<{ page?: string }>();
  const section = SECTIONS[page as keyof typeof SECTIONS] || SECTIONS.terms;

  return (
    <div className="min-h-screen bg-background">
      {/* Minimal nav */}
      <header className="sticky top-0 z-40 border-b border-border/40 bg-background/80 backdrop-blur-sm">
        <div className="mx-auto flex h-14 max-w-4xl items-center gap-4 px-6">
          <button
            onClick={() => navigate("/")}
            className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            <span className="text-sm">Back to Storvo</span>
          </button>
          <div className="ml-auto flex items-center gap-1">
            <button
              onClick={() => navigate("/legal/terms")}
              className={`rounded-lg px-3 py-1.5 text-sm transition-colors ${page === "terms" || !page ? "bg-accent font-medium text-foreground" : "text-muted-foreground hover:text-foreground"}`}
            >
              Terms
            </button>
            <button
              onClick={() => navigate("/legal/privacy")}
              className={`rounded-lg px-3 py-1.5 text-sm transition-colors ${page === "privacy" ? "bg-accent font-medium text-foreground" : "text-muted-foreground hover:text-foreground"}`}
            >
              Privacy
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-12">
        <div className="mb-10">
          <h1 className="font-display text-3xl font-extrabold text-foreground">{section.title}</h1>
          <p className="mt-2 text-sm text-muted-foreground">Last updated: {section.lastUpdated}</p>
          <p className="mt-4 text-sm text-muted-foreground leading-relaxed">
            These {section.title.toLowerCase()} govern your use of Storvo, a product of <strong className="text-foreground">LHF Studio</strong>.
          </p>
        </div>

        <div className="space-y-8">
          {section.content.map((item) => (
            <div key={item.heading}>
              <h2 className="font-display text-lg font-bold text-foreground mb-2">{item.heading}</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">{item.body}</p>
            </div>
          ))}
        </div>

        <div className="mt-16 border-t border-border pt-8 text-center">
          <img src={storvoLogo} alt="Storvo" className="mx-auto h-8 w-auto rounded border border-border/60 bg-card/80 p-1" />
          <p className="mt-3 text-xs text-muted-foreground">© {new Date().getFullYear()} Storvo · A product of LHF Studio</p>
        </div>
      </main>
    </div>
  );
};

export default Legal;
